import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(__dirname, '..', 'package.json'), 'utf8'));
const target = resolve(__dirname, '..', 'src', 'environments', 'version.ts');

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  `// Generated by scripts/write-version.mjs from package.json. Do not edit.\nexport const APP_VERSION = '${pkg.version}';\n`,
  'utf8',
);
