<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sextante.Modules.Financial.Application.Tests</RootNamespace>
    <AssemblyName>Sextante.Modules.Financial.Application.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modules\Financial\Sextante.Modules.Financial.Application\Sextante.Modules.Financial.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Financial\Sextante.Modules.Financial.Infrastructure\Sextante.Modules.Financial.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Financial\Sextante.Modules.Financial.Domain\Sextante.Modules.Financial.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Financial\Sextante.Modules.Financial.PublicApi\Sextante.Modules.Financial.PublicApi.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Identity\Sextante.Modules.Identity.PublicApi\Sextante.Modules.Identity.PublicApi.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\SharedKernel\Sextante.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Sextante.Infrastructure\Sextante.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
